FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server.py .
COPY static/ ./static/
COPY templates/ ./templates/
COPY image.png .

EXPOSE 5000

CMD ["python", "server.py"]